### ISSUE TITLE
MsSQL bad order when creating Guids in for loop

### ISSUE THREAD

**Issue by borisdj** [richardtallent/RT.Comb#5] opened 2017-03-28 14:08 UTC
This code:
```
ICombProvider SqlCombs = new SqlCombProvider(new SqlDateTimeStrategy());
for (int i = 0; i < 10; i++)
{
    string userEmail = $"user{i}@c.com";
    if (!context.Users.Any(a => a.Email == userEmail))
    {
        User user = new User
        {
            UserId = SqlCombs.Create(), // I tried also Create(DateTime.Now) but it didn't help
            Email = userEmail,
            TimeCreated = DateTime.Now 
        };
        context.Users.Add(user);
    } 
}
```
gives me following rows in Db:

> **UserId_________________________________________Email______________DateCreated**
7e9c3780-adf2-45fa-85e1-a74400db7571____user1@c.com____2017-03-28 15:19:01.4968188
b392329f-2a6b-4724-93fa-a74400db7571____user2@c.com____2017-03-28 15:19:01.4991283
1348112e-9b16-41b6-94bc-a74400db7572___user4@c.com____2017-03-28 15:19:01.5031330
0d782a85-d8ff-46a5-971d-a74400db7572____user3@c.com____2017-03-28 15:19:01.5011320
df7c503e-1992-404f-b128-a74400db7573____user5@c.com____2017-03-28 15:19:01.5051359
...

**user4** comes before **user3**.
I think that you need to have _lastSequence like it is used on the blog (line 87):
[http://www.siepman.nl/blog/post/2013/10/28/ID-Sequential-Guid-COMB-Vs-Int-Identity-using-Entity-Framework.aspx](http://www.siepman.nl/blog/post/2013/10/28/ID-Sequential-Guid-COMB-Vs-Int-Identity-using-Entity-Framework.aspx)

**Comment by richardtallent** [comment] 2017-03-28 18:34
Thanks for logging the issue.

This is expected behavior when using a timestamp-based COMB. The point of the COMB is *not* to preserve absolute insert order, it is to minimize database overhead on GUID-indexed inserts, while providing the side effect of a potentially useful embedded timestamp and a *rough* sortability by insert order.

It's also intended to be a stateless algorithm--one that can run on multiple clients or multiple application servers, writing into the same database, which is why we can't track and monotonically increment past values.

Another issue is that the `SqlDateTimeStrategy` uses a very specific byte layout that is intended to be compatible with the original COMB implementation and easy to translate back and forth to SQL Server's native `datetime` format. The `datetime` format is limited to a resolution of 1/300s, or about 3ms, and as described in the documentation under Security and Performance, the real-world resolution is lower:

> (6) When generating values, note that on Windows platforms, the Windows system timer only has a resolution of around 15ms. But even with a higher-resolution timer, multiple COMB values can have the same timestamp if you generate them quickly enough, so don't rely on the COMB alone if you need to sort your values in exactly the same order as they were created.

If you need *absolute* insert order preservation, COMB probably isn't going to be the right solution. You can use `NEWSEQUENTIALID()`, but it is impacted by reboots and of course doesn't scale to multiple server instances. The code you posted would work, but only if you have a single instance of that code writing into the database (no load-balanced application servers, no clients connecting directly, etc.).

If you don't need compatibility with the original COMB concept and `datetime` type, I would suggest the following:

1. Use `SqlCombProvider` with the `UnixDateTimeStrategy`. This provides 1ms resolution (of course, further limited to your system's clock) rather than the ~3ms of `SqlDateTimeStrategy`.

2. If you need to create a number of COMBs in a tight loop and be able to sort them in the absolute order of insert, you could do something like this:

```
ICombProvider SqlCombs = new SqlCombProvider(new UnixDateTimeStrategy());
var baseDateTime = DateTime.UtcNow;
for (int i = 0; i < 10; i++)
{
    string userEmail = $"user{i}@c.com";
    if (!context.Users.Any(a => a.Email == userEmail))
    {
        User user = new User
        {
            UserId = SqlCombs.Create(baseDateTime.addMilliseconds(i)),
            Email = userEmail,
            TimeCreated = DateTime.Now 
        };
        context.Users.Add(user);
    } 
}
```

While not the "true" timestamp for each record, the surrogate timestamp should sort correctly. This is untested code, but hopefully you get the idea.

Hope that helps!

Since this library is implemented now using a Singleton pattern rather than static methods, it may be possible to write in an *option* that would never use the same timestamp twice (for the same SqlComb instance), using a version of the above concept of faking some added milliseconds when a time collision is detected. I'm waiting for things to settle down a little on `csproj` support in VS Code and Nuget, so I may write in that extra option when I sit down to convert the project files. I'll keep this item open until then.

**Comment by borisdj** [comment] 2017-03-28 20:02
In the example above I have simplified code just to point the logic.
My real case is that I have SeqGuid class which encapsulates sequential Guid creation and I need it that way.
It would be like this
```
public static class SeqGuid
{
    public static Guid Create()
    {
        ICombProvider SqlCombs = new SqlCombProvider(new UnixDateTimeStrategy());
        return SqlCombs.Create(DateTime.UtcNow);
    }
}

class Program
{
    static void Main(string[] args)
    {
        var list = new List<User>();
        for (int i = 0; i < 10; i++)
        {
            var now = DateTime.Now;
            User userN = new User
            {
                UserId = SeqGuid.Create(),
                Email = $"user{i}@c.com";,
		TimeCreated = DateTime.UtcNow
            };
        list.Add(userN);
    }
}
```

As you can see index 'i' is not in the scope of SeqGuid and I want to keep ti as simple as SeqGuid.Create().

I do NOT need COMB compatibility.
We use Guids for PKs so we want them sorted for clustered index efficiency and secondly we sometimes use their order for some report so absolute order is also required.
NEWSEQUENTIALID() is not an options because of reboots.
We have single server instance so lastSequence works in our scenario.

At the moment we are actually using code from this blog but I was thinking to switch to this library since it's already in nuget.
However seems that it can't be used for this scenario at the moment, correct me if I'm wrong.

It would be interesting if you could add the same feature to be configurable in this library.
I read that in May this year .Net Standard 2.0 (supporting both .NetCore and .Net 4.6.1+) will be released so if you plan to switch the library to it then you could add this option as well.
Maybe adding another strategy, for example named SqlSequentialDateTimeStrategy();

In any case nice work.

**Comment by richardtallent** [comment] 2017-03-29 05:38
I needed to clean up a few things anyway, so I released a new version with a workaround for this issue. Just posted to NuGet as well.

Basically, I added a delegate to `ICombProvider` that provides `Create()` the timestamp to use when one isn't passed. Then, I created an optional delegate implementation `UtcNoRepeatTimestampProvider` that works in a similar way to the code you linked to. It still returns the UTC timestamp, but slides the time as needed to ensure it never returns the same timestamp value twice.

Check out the last unit test, it shows example code of how to do this (and proves it works in a tight loop generating 1000 COMBs).

Since you don't need original COMB compatibility, I definitely recommend using UnixDateTimeStrategy, which will give you 1ms resolution inside the COMB, and set `UtcNoRepeatTimestampProvider.IncrementMs` to 1ms as well so it doesn't skip more time than necessary to provide unique, sequential values.

Moving to .Net Standard 2.0 is on my list, but I'll still probably have a build for 4.5.1 since many people can't go to 4.6 yet. That will happen when I upgrade the project files.

Closing the issue, please feel free to open again if this doesn't solve the problem for you.

**Closed by richardtallent** 2017-03-29 05:38 UTC

**Comment by borisdj** [comment] 2017-03-29 08:18
I figured I could implement _lastSequence in my SeqGuid class as a Workaround.
But since you already integrate it here, workaround won't be necessary.
And I can confirm it works well.

There is one more thing here worth mentioning and that is the timespan resolution.
We are working on existing database which already has data, where Guids were created with code from previous blog and I need to keep old record to be 'before' the new ones.
In this library timespan was from 2011 to 2100 so that.
Because of this I can now use only `SqlDateTimeStrategy` and not `UnixDateTimeStrategy`, so that the order is correctly preserved.
